Task5.2
Feodoros/FSharpLitvinovGroup pull request #17
Opened 2019-04-14 23:02 UTC by Feodoros

2019-06-07 13:33 UTC, yurii-litvinov requested changes

2019-06-07 13:33 UTC, yurii-litvinov commented on task5.2/task5.2_tests/Program.fs
> +        (List.map (fun y -> y * num) list) = (|>) List.map ((>>) (*)) num list
Списывать нехорошо и тут ерунда написана :)

2019-06-07 14:43 UTC, Feodoros commented on task5.2/task5.2_tests/Program.fs
> +        (List.map (fun y -> y * num) list) = (|>) List.map ((>>) (*)) num list
Вообще саму программу я первее всех написал и потом куда-то скидывал, но на гит залил позже из-за фсчека. Вот спросил только как с ним работать. А что поправить?

2019-06-09 16:22 UTC, yurii-litvinov approved these changes
Окей, зачтена

2019-06-09 16:22 UTC, yurii-litvinov commented on task5.2/task5.2_tests/Program.fs
> +        (|>) List.map ((>>) (*)) 10 [0..5] |> should equal [0; 10; 20; 30; 40; 50]
А этот тест не поправили :)

2019-06-09 16:22 UTC, yurii-litvinov commented on task5.2/task5.2_tests/Program.fs
> +        (List.map (fun y -> y * num) list) = funcFinal() num list
Лучше, наверное, funcStart вместо List.map (fun y -> y * num) list

2019-11-01 19:43 UTC, merged