Initial commit.
Feodoros/FSharpLitvinovGroup pull request #2
Opened 2019-02-22 12:56 UTC by Feodoros

2019-02-22 12:59 UTC, yurii-litvinov requested changes

2019-02-22 12:59 UTC, yurii-litvinov commented on Fibonacchi.fs
> +    if n > 3 then fib (n-1) + fib (n-2)
Это не за линейное время, и со стайлгайдом беда :)

2019-02-23 20:33 UTC, Feodoros commented on Fibonacchi.fs
> +    if n > 3 then fib (n-1) + fib (n-2)
Понял. Новую версию скинул на hw.

2019-02-23 22:58 UTC, yurii-litvinov approved these changes
Со стайлгайдом всё ещё беда, но не такая страшная. Зачтена

2019-02-23 22:58 UTC, yurii-litvinov commented on Fibonacchi.fs
> +let Fibonacci index =
Функции в F# по традиции именуются со строчной

2019-02-23 22:58 UTC, yurii-litvinov commented on Fibonacchi.fs
> +    | false, _ -> printfn "Waiting for integer number."; readInteger()
Надо один оператор на одной строке,
```fsharp
| false, _ -> printfn "Waiting for integer number."
              readInteger()
```

2019-02-23 22:58 UTC, yurii-litvinov commented on Fibonacchi.fs
> +            loop decreaser firstPrevious sum
Можно было просто `loop (counter - 1) firstPrevious (secondPrevious + firstPrevious)`, но можно и так

2019-02-24 18:29 UTC, Feodoros commented on Fibonacchi.fs
> +            loop decreaser firstPrevious sum
Точно, отличная идея. Спасибо :)

2019-02-24 18:48 UTC, merged