Task3.1
Feodoros/FSharpLitvinovGroup pull request #8
Opened 2019-03-03 23:49 UTC by Feodoros

2019-04-11 10:47 UTC, yurii-litvinov requested changes
Надо немного поправить

2019-04-11 10:47 UTC, yurii-litvinov commented on Task3.1/Task3.1/evenNumInList.fs
> +        List.length list - List.sum (List.map (fun x -> abs (x % 2)) list)
А можете проще, без List.length -- только через List.sum, List.map и некоторое количество теории чисел? :)

2019-04-11 10:47 UTC, yurii-litvinov commented on Task3.1/Task3.1/evenNumInList.fs
> +//Вычитаем из полного количества элементов количество нечетных элементов (нечет % 2 по модулю = 1, складываем эти единицы)
Символ комментария отделяется пробелом от текста комментария. И тут лучше комментарий в формате XML Documentation, через `///`

2019-04-11 10:47 UTC, yurii-litvinov commented on Task3.1/Task3.1/evenNumInList.fs
> +//Вычитаем из полного количества элементов количество нечетных элементов (нечет % 2 по модулю = 1, складываем эти единицы)
Ну и отступ комментария должен соответствовать отступу комментируемой сущности

2019-04-11 10:47 UTC, yurii-litvinov commented on Task3.1/Task3.1_test/evenNumInList_tests.fs
> +        evenNumWithFold [] |> should equal 0
Здесь бы QuickCheck, проверяющий, что функции возвращают одинаковые результаты.

2019-04-11 10:47 UTC, yurii-litvinov commented on Task3.1/Task3.1/evenNumInList.fs
> +﻿module logic
Модули именуются с заглавной

2019-04-12 00:28 UTC, Feodoros commented on Task3.1/Task3.1/evenNumInList.fs
> +        List.length list - List.sum (List.map (fun x -> abs (x % 2)) list)
Сделаю! :)

2019-06-01 08:56 UTC, yurii-litvinov approved these changes
Окей, зачтена

2019-06-01 08:56 UTC, yurii-litvinov commented on Task3.1/Task3.1/evenNumInList.fs
> +    ///Делаем из четных нечетные, берем остаток от деления по модулю (1) и суммируем.
Символ комментария отделяется пробелом от текста комментария, `/// Делаем`

2019-10-23 20:48 UTC, merged